trigger:
- dev

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: BuildStage
    jobs:
    - job: Build
      steps:
        - task: NodeTool@0
          displayName: 'Install Node js'
          inputs:
            versionSpec: '18.x'
        
        - script: |
            cd SecondAngularApp/
            npm install -g @angular/cli
            npm install
            ng build 
          displayName: 'npm install and build'
          workingDirectory: '$(Build.SourcesDirectory)'

        -  task: CmdLine@2
           displayName: "Run unit tests"
           inputs:
            script: |
              cd SecondAngularApp/
              ng test --browsers=ChromeHeadless --code-coverage --watch=false

        -  task: ArchiveFiles@2
           displayName: 'Archive files'
           inputs:
            rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/Second-Angular-App/'
            includeRootFolder: false
            archiveType: zip
            archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            replaceExistingArchive: true

        -  task: PublishBuildArtifacts@1
           inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
            ArtifactName: 'drop'
            publishLocation: 'Container'


