trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Install Node js'
  inputs:
    versionSpec: '18.x'
- task: Npm@1
  displayName: 'Installing NPM'
  inputs:
    command: 'install'

- task: Npm@1
  displayName: 'publishing'
  inputs:
    command: 'publish'
    publishRegistry: 'useFeed'
    publishFeed: 'b254523d-9051-4c3b-9b49-08bf84ff0348'
